#!/bin/bash

export Cellar=$(brew --cellar socios)


#Installation of VirtualBox

function check {
	source $Cellar/*/lib/install_virtualbox.scpt
}

#Building VirtualBox_VM

function createvm {
	source $Cellar/*/lib/create_vm.sh
}

#Display Help_Menu

function help {
	echo "Socios - experience Linux with you Mac."
	echo "Usage: socios [options...]"
	echo
	echo "Valid options are:"
	echo "--build        Create the virtual machine in VirtualBox"
	echo "--check        Check the environment to install Socios"
	echo "--help         Print this Help menu"
	echo "--version      Print the current version"	
}

########################################
#Socios options passing with Arguments #
########################################

for arg in "$@"; do
  if [[ "$arg" = --check ]]; then
	check
  fi
  if [[ "$arg" = --build ]]; then
	createvm
  fi
  if [[ "$arg" = --help ]]; then
	help
  fi
done
########################################
